# Generated by Django 5.2.17 on 2026-09-07 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('channel_type', models.CharField(choices=[('telegram', 'Telegram'), ('lk_webhook', 'ЛК (вебхук)'), ('lk_api', 'ЛК (API)')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Канал публикации',
                'verbose_name_plural': 'Каналы публикации',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url', models.URLField(max_length=1000, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('source_published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('duplicate', 'Дубликат'), ('pending_moderation', 'На модерации'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('published', 'Опубликована')], default='new', max_length=20)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_comment', models.TextField(blank=True)),
                ('edited_title', models.CharField(blank=True, max_length=500)),
                ('edited_post_text', models.TextField(blank=True)),
                ('editor_verdict', models.CharField(blank=True, choices=[('publish', 'publish'), ('reject', 'reject')], max_length=10, null=True)),
                ('editor_processed_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_requeue_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='sources.category')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='news.article')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_articles', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='sources.source')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='PublicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed')], max_length=10)),
                ('response_snippet', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_logs', to='news.article')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_logs', to='news.publishchannel')),
            ],
            options={
                'verbose_name': 'Лог публикации',
                'verbose_name_plural': 'Логи публикаций',
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'source_published_at'], name='news_articl_status_e56a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'is_urgent', 'source_published_at'], name='news_articl_status_3a1f9e_idx'),
        ),
    ]
