# Generated by Django 5.2.17 on 2026-09-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='lk_category',
            field=models.CharField(choices=[('club', 'Клуб'), ('world_cup', 'Кубок мира'), ('resort_cis', 'Курорты СНГ'), ('resort_asia', 'Курорты Азии'), ('resort_europe', 'Курорты Европы'), ('resort_americas', 'Курорты Америки')], default='resort_cis', max_length=20),
        ),
    ]
