# Generated by Django 5.2.17 on 2026-09-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_source_lk_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('rss', 'RSS'), ('html', 'HTML'), ('manual', 'Ручной ввод (модератор)')], max_length=10),
        ),
    ]
